---

# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts: 127.0.0.1
  port: 9200
  url_prefix:
  use_ssl:
  certificate:
  client_cert:
  client_key:
  ssl_no_validate:
  http_auth:
  timeout: 30
  master_only: True

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
